# Generated by Django 5.1.3 on 2024-11-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('floor', models.CharField(max_length=10)),
            ],
        ),
    ]
